### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by retif** [o0Ignition0o/airsim-rs#1]
Hello, Jeremy, please share your gmail, i would like to talk with you about AirSim(ive seen your comments on my AirSim macos catalina issue)

**Comment by o0Ignition0o** [comment]
Hey :) sure my gmail is jeremy dot lempereur at gmail dot com. 

For now I’ve been able to run this crate (which I need to clean up/document/add tests to) against the unity and the unreal blocks simulator, with quite a bit of quirks at various steps of the run (won’t close, freezes the computer etc. Depending on which version) as you can see here:

https://media.discordapp.net/attachments/663463674047889428/674375133338533918/Screen_Recording_2020-02-04_at_23.01.29.mov 

I would love to talk more about it / spend more time on it though !

**Comment by o0Ignition0o** [comment]
Hey there :) how's it going ? I'm starting to get some pretty cool results with the car simulator, and streaming my way through it on twitch: https://www.twitch.tv/videos/556670637
Hope to read from you soon !
